name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - uses: xu-cheng/texlive-action@v3
        with:
          run: |
            pdflatex -shell-escape -interaction=batchmode curso-latex.tex
            biber --input-directory tex curso-latex
            pdflatex -shell-escape -interaction=batchmode curso-latex.tex
            pdflatex -shell-escape -interaction=batchmode curso-latex.tex
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: curso-latex.pdf
      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          # overwrite_files: true
          files: curso-latex.pdf